//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieptDetail
    {
       public long Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string RecieptNo { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Discount { get; set; }
        public string BankName { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
